package extractors

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/dvordrova/repomap/internal/corpus"
	"github.com/dvordrova/repomap/internal/facts"
)

func TestSQLCConnectsConfigInputsAndOutputsWithoutGit(t *testing.T) {
	root, repository := newCorpus(t, map[string]string{
		"db/sqlc.yaml":                "version: '2'\nsql:\n- engine: postgresql\n  schema: [../migrations, schema.sql]\n  queries: queries\n  gen:\n    go:\n      out: generated\n- engine: sqlite\n  schema: other.sql\n  queries: other.sql\n  codegen:\n  - plugin: python\n    out: ../client\n",
		"migrations/001.up.sql":       "CREATE TABLE authors (id bigint);\n",
		"migrations/001.down.sql":     "DROP TABLE authors;\n",
		"db/schema.sql":               "CREATE TABLE books (id bigint);\n",
		"db/queries/authors.sql":      "-- name: Get :one\nSELECT * FROM authors;\n",
		"db/generated/authors.sql.go": "// Code generated by sqlc. DO NOT EDIT.\npackage generated\n",
		"db/generated/manual.go":      "package generated\n",
		".gitignore":                  "db/generated/\n",
	})
	result := buildFacts(t, root, repository)
	nodes := map[string]facts.Fact{}
	for _, node := range result.OfKind(facts.KindEntity) {
		nodes[node.Key] = node
	}
	if nodes["path:migrations"].Value != "present" || len(nodes["path:migrations"].Evidence) != 2 {
		t.Fatal("migration members lost")
	}
	if nodes["path:db/generated"].Value != "present" || len(nodes["path:db/generated"].Evidence) != 2 {
		t.Fatal("untracked output members lost")
	}
	if nodes["path:client"].Value != "not_in_corpus" {
		t.Fatal("missing output disappeared")
	}
	var links []facts.Fact
	for _, row := range result.OfKind(facts.KindRelation) {
		if row.Extractor == "sqlc" {
			links = append(links, row)
		}
	}
	if len(links) != 7 {
		t.Fatalf("links = %+v", links)
	}
	byID := result.ByID()
	for _, link := range links {
		if link.Extractor != "sqlc" || link.Anchor.Path != "db/sqlc.yaml" {
			t.Fatalf("link origin = %+v", link)
		}
		if link.Key == "configured queries input" && byID[link.Refs[0]].Key == "db/sqlc.yaml#sql[0]" {
			if link.Anchor.Line != 5 || byID[link.Refs[1]].Path != "db/queries" {
				t.Fatalf("query anchor = %+v", link)
			}
		}
	}
	if again := buildFacts(t, root, repository); !reflect.DeepEqual(result, again) {
		t.Fatal("nondeterministic extraction")
	}
}

func TestSQLCUnresolvedPathsRemainNamedReferences(t *testing.T) {
	root, repository := newCorpus(t, map[string]string{"sqlc.json": `{"version":"2","sql":[{"engine":"sqlite","schema":"../other/schema.sql","queries":"queries/*.sql","gen":{"go":{"out":"generated"}}}]}`})
	result := buildFacts(t, root, repository)
	count := 0
	for _, node := range result.OfKind(facts.KindEntity) {
		if node.Value == "reference" {
			count++
			if node.Path != "" || node.Symbol == "" {
				t.Fatalf("invented path: %+v", node)
			}
		}
	}
	if count != 2 || len(result.OfKind(facts.KindRelation)) != 3 || len(result.Diagnostics) != 2 {
		t.Fatalf("unresolved references lost: %+v", result)
	}
}

func TestSQLCRefusesUnsupportedOrIncompleteConfig(t *testing.T) {
	for _, config := range []string{"version: '1'\npackages: []", "version: '2'\nsql: [{engine: sqlite, schema: 123, queries: q.sql, gen: {go: {out: gen}}}]", "version: '2'\nversion: '2'\nsql: []"} {
		root, repository := newCorpus(t, map[string]string{"sqlc.yaml": config})
		result := buildFacts(t, root, repository)
		if len(result.OfKind(facts.KindEntity)) != 0 || len(result.Diagnostics) == 0 {
			t.Fatal("invalid config silently interpreted")
		}
	}
}

func buildFacts(t *testing.T, root string, repository *corpus.Corpus) facts.Result {
	t.Helper()
	extracted, err := Run(context.Background(), root, repository)
	if err != nil {
		t.Fatal(err)
	}
	result, err := facts.Build(facts.Input{Repository: repository, Extractions: extracted.Extractions})
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func newCorpus(t *testing.T, files map[string]string) (string, *corpus.Corpus) {
	t.Helper()
	root := t.TempDir()
	for name, content := range files {
		full := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	repository, err := corpus.Open(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = repository.Close() })
	return root, repository
}
