import { build } from 'esbuild';
import { readFile, writeFile, readdir } from 'node:fs/promises';

// Checked-in output is part of the Go module. Neither go build nor go install
// invokes this build, accesses npm, or requires Node on the reader's machine.
const result = await build({
  entryPoints: ['canvas.jsx'], bundle: true, minify: true, write: false,
  format: 'iife', target: ['es2022'], outfile: 'report-ui.js', metafile:true,
  define: { 'process.env.NODE_ENV': '"production"' }, legalComments: 'inline',
  // Only the browser build uses a real worker. Node tests retain elk.bundled
  // and execute the same native layout engine without browser globals.
  alias: {'elkjs/lib/elk.bundled.js':'./elk-browser.mjs'},
  plugins: [{name:'embedded-elk-worker', setup(build) {
    build.onLoad({filter:/elk-worker\.min\.js$/}, async ({path})=>({
      contents:await readFile(path,'utf8'), loader:'text',
    }));
  }}],
});
const packages=new Set(Object.keys(result.metafile.inputs).filter(p=>p.startsWith('node_modules/')).map(p=>p.split('/').slice(0,p.split('/')[1].startsWith('@')?3:2).join('/')));
let notices='';
for(const root of [...packages].sort()) {
  const pkg=JSON.parse(await readFile(`${root}/package.json`,'utf8'));
  notices+=`\n${pkg.name} ${pkg.version} (${pkg.license||'see license'})\nSource: https://registry.npmjs.org/${pkg.name}/-/${pkg.name.split('/').at(-1)}-${pkg.version}.tgz\n`;
  for(const file of (await readdir(root)).filter(f=>/^licen[sc]e(\.|$)/i.test(f)))notices+=await readFile(`${root}/${file}`,'utf8');
}
for (const file of result.outputFiles) {
  const css = file.path.endsWith('.css');
  const path = css ? '../templates/css/47-flow.css' : '../templates/js/27-report-ui.js';
  const text = '/* Generated by internal/report/web/build.mjs; edit web/ sources. */\n' + file.text +
    (css?'':`\n/* Bundled dependency notices\n${notices.replaceAll('*/','* /').replaceAll('</script','<\\/script')}\n*/\n`);
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== text) throw new Error(`${path} needs npm run build`);
  } else await writeFile(path, text);
}
