// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package handler

import "example.com/echo-sqlc-service/internal/users/model"

type ConverterImpl struct{}

func (converter *ConverterImpl) ToResponse(source model.User) UserResponse {
	var response UserResponse
	response.ID = source.ID
	response.Name = source.Name
	return response
}
