package places

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/dvordrova/repomap/internal/atlas"
	"github.com/dvordrova/repomap/internal/corpus"
	"github.com/dvordrova/repomap/internal/extractors"
	"github.com/dvordrova/repomap/internal/facts"
)

func TestExtractionGraphPreservesDeclarationsAndInventorySeparately(t *testing.T) {
	root := t.TempDir()
	for path, content := range map[string]string{
		"sqlc.yaml":           "version: '2'\nsql:\n- engine: sqlite\n  schema: migrations\n  queries: queries.sql\n  gen:\n    go:\n      out: generated\n- engine: sqlite\n  schema: missing.sql\n  queries: queries.sql\n  gen:\n    go:\n      out: absent\n",
		"migrations/001.sql":  "CREATE TABLE users(id integer);",
		"queries.sql":         "-- name: List :many\nSELECT * FROM users;",
		"generated/db.go":     "// Code generated by sqlc. DO NOT EDIT.\npackage generated",
		"generated/manual.go": "package generated",
	} {
		full := filepath.Join(root, path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	repository, err := corpus.Open(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	defer repository.Close()
	extracted, err := extractors.Run(context.Background(), root, repository)
	if err != nil {
		t.Fatal(err)
	}
	// A company tool returning the exact same data uses the identical path.
	company := extracted.Extractions[0]
	company.Name = "company"
	extracted.Extractions = append(extracted.Extractions, company)
	result, err := facts.Build(facts.Input{Repository: repository, Extractions: extracted.Extractions})
	if err != nil {
		t.Fatal(err)
	}
	graph := atlas.Graph{Version: atlas.GraphVersion, Places: []atlas.Place{}, Edges: []atlas.Edge{}, Seeds: []string{}}
	b := &builder{input: Input{Facts: result}, files: map[string]*fileState{}}
	for _, path := range []string{"generated/db.go", "generated/manual.go"} {
		b.files[path] = &fileState{targets: map[string]struct{}{"target": {}}}
		graph.Places = append(graph.Places, atlas.Place{ID: atlas.FileID(path), Kind: atlas.PlaceFile, Path: path, File: &atlas.FileFacts{Generated: path == "generated/db.go"}})
	}
	b.addExtractions(&graph)
	atlas.SortPlaces(graph.Places)
	encoded, err := atlas.EncodeGraph(graph)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := atlas.DecodeGraph(encoded); err != nil {
		t.Fatal(err)
	}
	counts := map[string]int{}
	for _, edge := range graph.Edges {
		if len(edge.Witnesses) != 0 {
			t.Fatal("producer observation became a call")
		}
		counts[edge.Kind]++
		if edge.Kind == "observation" && (edge.Evidence.Path != "sqlc.yaml" || edge.Evidence.LineNo < 4) {
			t.Fatalf("lost exact source: %+v", edge)
		}
	}
	if counts["observation"] != 12 || counts["inventory"] != 4 {
		t.Fatalf("edges: %v", counts)
	}
	nodes := map[string]atlas.Place{}
	for _, place := range graph.Places {
		if place.Entity != nil {
			nodes[place.Entity.Extractor+":"+place.Path] = place
		}
		if place.Path == "generated/manual.go" && place.File.Generated {
			t.Fatal("manual file promoted to generated")
		}
	}
	for _, producer := range []string{"sqlc", "company"} {
		if node := nodes[producer+":generated"]; !reflect.DeepEqual(node.Entity.Files, []string{"generated/db.go", "generated/manual.go"}) || !reflect.DeepEqual(node.TargetIDs, []string{"target"}) {
			t.Fatalf("inventory lost: %+v", node)
		}
		if node := nodes[producer+":absent"]; node.Entity.Status != "not_in_corpus" || len(node.Entity.Files) != 0 {
			t.Fatalf("missing output lost: %+v", node)
		}
	}
}
