// Code generated by sqlc. DO NOT EDIT.
package sqlc

import "context"

const getUser = `-- name: GetUser :one
SELECT id, name
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var user User
	err := row.Scan(&user.ID, &user.Name)
	return user, err
}
